spring:
  data:
    redis:
      repositories:
        enabled: false
    #邮箱验证码配置
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 2351729294@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: atjtenhutnycdjji #刚刚生成的密钥
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
#  mail:
#    #smtp服务主机  qq邮箱则为smtp.qq.com;163邮箱是smtp.163.com
#    host: smtp.qq.com
#    #服务协议
#    protocol: smtp
#    # 编码集
#    default-encoding: UTF-8
#    #发送邮件的账户
#    username: 2351729294@qq.com
#    #授权码
#    password: atjtenhutnycdjji
#    test-connection: true
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true

